# -*- coding: utf-8 -*-
"""BaseDeDados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aFKsQqbGbzGkwru86Iop4J239Tt-s6PP

## 0. Preparação do ambiente

> **Nota para o professor:** em Colab, prefira ativar GPU em `Ambiente de execução > Alterar tipo de ambiente de execução > T4 GPU`.
"""

!pip -q install datasets transformers sentence-transformers

import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, ConfusionMatrixDisplay
from sklearn.ensemble import IsolationForest

from pandas.plotting import parallel_coordinates

RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)
random.seed(RANDOM_STATE)

pd.set_option("display.max_columns", 100)

"""# 1. EDA em dados tabulares: Wine

## Pergunta

**As características químicas dos vinhos formam padrões compatíveis com suas classes?**

Essa pergunta deve orientar toda a exploração.
"""

from sklearn.datasets import load_wine

wine = load_wine(as_frame=True)
df_wine = wine.frame.copy()
df_wine["class_name"] = df_wine["target"].map(dict(enumerate(wine.target_names)))

df_wine.head()

"""### 1.1 Unidade de análise e estrutura

Antes de calcular qualquer estatística, responda:

- O que representa cada linha?
- O que representa cada coluna?
- Qual é a variável de classe?
- Quais atributos são numéricos?

Precisamos da descrição do [dataset](https://archive.ics.uci.edu/dataset/109/wine)
"""

from sklearn.datasets import load_wine

wine = load_wine(as_frame=True)
print(wine.DESCR)

print("Dimensão:", df_wine.shape)
print("\nColunas:")
print(df_wine.columns.tolist())
print("\nTipos:")
print(df_wine.dtypes)

"""### 1.2 Perfil inicial

> **Pergunta:** o que `describe()` consegue responder? E o que ele não consegue?
"""

display(df_wine.describe().T)

print("Distribuição das classes:")
display(df_wine["class_name"].value_counts())

print("\nValores ausentes:")
display(df_wine.isna().sum().sort_values(ascending=False).head())

print("\nDuplicatas:")
print(df_wine.duplicated().sum())

"""- `describe()` descreve cada variável numericamente. Ele não explica a **estrutura dos dados**.
- distribuição, relação entre atributos, classes, outliers etc.

### 1.3 Distribuições e outliers

> Vamos discretizar os atributos em intervalos fixos de 20 valores (bins) e calcular a frequencia de valores em cada intervalo. Isso faz com que diminuimos a quantidade de valores do atributo por exemplo de 178 valores diferentes para 20 valores.
"""

features_to_plot = ["alcohol", "malic_acid", "magnesium", "color_intensity", "proline"]

for col in features_to_plot:
    plt.figure(figsize=(8,4))

    counts, bins, patches = plt.hist(
        df_wine[col],
        bins=20,
        edgecolor="black"
    )

    for count, patch in zip(counts, patches):
        plt.text(
            patch.get_x() + patch.get_width()/2,
            count,
            str(int(count)),
            ha="center",
            va="bottom",
            fontsize=8
        )

    # Imprimir os intervalos e frequências
    print(f"\nBins da variável: {col}")

    for i in range(len(counts)):
        print(
            f"Bin {i+1:2d}: "
            f"[{bins[i]:.2f}, {bins[i+1]:.2f}) "
            f"→ {int(counts[i])} amostras"
        )
    plt.title(f"Distribuição: {col}")
    plt.xlabel(col)
    plt.ylabel("Frequência")
    plt.show()

for col in features_to_plot:
    plt.figure(figsize=(6,2.8))
    df_wine.boxplot(column=col)
    plt.title(f"Boxplot: {col}")
    plt.suptitle("")
    plt.show()

"""### 1.4 Parallel coordinates

Como as escalas das features são muito diferentes, padronizamos antes. Essa padronização visa alterar a escala dos valores dos atributos para evitar que determinados atributos tenham valores que dominem outros atributos. Todos os atributos agora estão variando de -4 a +4.

> **Pergunta:** quais atributos parecem mostrar padrões diferentes entre as classes?
"""

feature_cols = wine.feature_names

# Padronização Z-Score
X_scaled = StandardScaler().fit_transform(df_wine[feature_cols])

df_parallel = pd.DataFrame(X_scaled, columns=feature_cols)
df_parallel["class_name"] = df_wine["class_name"].values

# Amostrar 20 exemplos de cada classe
parts = []

for class_name, group in df_parallel.groupby("class_name"):
    parts.append(
        group.sample(
            min(len(group), 20),
            random_state=RANDOM_STATE
        )
    )

sample_parallel = pd.concat(parts).reset_index(drop=True)


# Parallel Coordinates
plt.figure(figsize=(16, 7))

parallel_coordinates(
    sample_parallel,
    class_column="class_name",
    color=["red", "green", "blue"],
    alpha=0.70,       # menos transparente
    linewidth=1.5     # linhas mais espessas
)

plt.xticks(rotation=70)
plt.title(
    "Wine — Parallel Coordinates (features padronizadas)",
    fontsize=16
)

plt.ylabel("Z-Score")
plt.grid(alpha=0.2)

plt.tight_layout()
plt.show()

"""### Discussão

- Existem features visualmente mais discriminativas?
- Existem regiões de forte sobreposição?
- Um gráfico como este é suficiente para concluir que as classes são separáveis?
- O que acontece quando temos centenas de dimensões?

# 2. Qualidade dos dados: vamos sabotar a base

Bases didáticas costumam ser limpas demais. Em projetos reais encontramos:

- valores ausentes;
- duplicatas;
- tipos incorretos;
- categorias inconsistentes;
- ruído;
- outliers.
"""

df_dirty = df_wine.copy()

# Missing values artificiais
for col in ["alcohol", "malic_acid", "magnesium"]:
    idx = np.random.choice(df_dirty.index, size=5, replace=False)
    df_dirty.loc[idx, col] = np.nan

# Duplicatas
df_dirty = pd.concat([df_dirty, df_dirty.iloc[:5]], ignore_index=True)

# Outliers artificiais
df_dirty.loc[0, "magnesium"] = df_dirty["magnesium"].median() * 8
df_dirty.loc[1, "color_intensity"] = df_dirty["color_intensity"].median() * 10
print("Outliers nas linhas: 0 e 1")

# Ruído em uma feature
noise_idx = np.random.choice(df_dirty.index, size=10, replace=False)
print("Ruído nas linhas:", noise_idx)
df_dirty.loc[noise_idx, "proline"] += np.random.normal(0, 800, size=10)

print("Shape após sabotagem:", df_dirty.shape)

print("Valores ausentes:")
display(df_dirty.isna().sum().sort_values(ascending=False).head(10))

print("\nDuplicatas:")
print(df_dirty.duplicated().sum())

print("\nResumo:")
display(df_dirty.describe().T)

"""### 2.1 Outliers por IQR

> **Importante:** outlier estatístico não significa automaticamente erro.
"""

def iqr_outliers(series):
    s = series.dropna()
    q1, q3 = s.quantile([0.25, 0.75])
    iqr = q3 - q1
    lower = q1 - 1.5 * iqr
    upper = q3 + 1.5 * iqr
    return s[(s < lower) | (s > upper)]

print("Cenários atipicos que merecem atenção:\n")
for col in ["magnesium", "color_intensity", "proline"]:
    outs = iqr_outliers(df_dirty[col])
    print(f"{col}: {len(outs)} candidatos a outlier")

"""### 2.2 Outliers multivariados com Isolation Forest

Aqui usamos o algoritmo como **ferramenta de investigação**, não como verdade absoluta.
"""

clean_num = df_dirty[feature_cols].dropna()

iso = IsolationForest(contamination=0.05, random_state=RANDOM_STATE)
pred = iso.fit_predict(StandardScaler().fit_transform(clean_num))


outlier_idx = clean_num.index[pred == -1]
#df_dirty.loc[outlier_idx, ["class_name"] + feature_cols[:5]].head(10)
df_dirty.loc[outlier_idx, ["class_name"] + feature_cols]

X_clean_scaled = StandardScaler().fit_transform(clean_num)

iso = IsolationForest(
    contamination=0.05,
    random_state=RANDOM_STATE
)

pred = iso.fit_predict(X_clean_scaled)

scores = iso.decision_function(X_clean_scaled)

resultado = clean_num.copy()
resultado["class_name"] = df_dirty.loc[clean_num.index, "class_name"]
resultado["prediction"] = pred # -1 anomalo ou 1 normal
resultado["anomaly_score"] = scores #O quão anomalo são as instâncias? quanto menor ou negativo mais confiança sobre a anomalia

resultado[resultado["prediction"] == -1] \
    .sort_values("anomaly_score")

"""### Perguntas para discussão

- Um ponto extremo é necessariamente inválido?
- Em quais situações devemos remover um outlier?
- Quando um outlier pode ser justamente o fenômeno mais interessante?
- Como valores ausentes podem afetar visualizações e modelos?

Essas estratégias nos apresentaram cenários que merecem a nossa atenção. A maioria desses cenários são aqueles que introduzimos artificialmente, mas se não tivessemos feito isso, essas estratégias poderiam nos dar a luz para identificar situação candidatas anomalas.

# 3. Imagens: de pixels para features com DINOv2

## Dataset: Beans

Classes:

- `angular_leaf_spot`
- `bean_rust`
- `healthy`

## Pergunta

**As representações aprendidas pelo DINOv2 tornam essas classes visualmente separáveis no espaço de features?**

Fluxo:

**Imagem → DINOv2 → embedding**
"""

from datasets import load_dataset

beans = load_dataset("AI-Lab-Makerere/beans") #Tem que criar uma conta no hugginface e gerar um token para acesso remoto.
beans

label_feature = beans["train"].features["labels"]
beans_label_names = label_feature.names
print(beans_label_names)

"""### 3.1 Amostragem pequena para manter a aula rápida"""

selected = []
# Load the entire 'train' split to ensure > 1000 samples
for label_id, label_name in enumerate(beans_label_names):
    subset = beans["train"].filter(lambda x: x["labels"] == label_id)
    selected.extend([subset[i] for i in range(len(subset))])

# Shuffle the entire selected list once to randomize the order
random.shuffle(selected)

print("Total de imagens:", len(selected))

"""### 3.2 Observe os dados brutos antes dos embeddings"""

fig, axes = plt.subplots(3, 4, figsize=(10,8))
for ax, item in zip(axes.flat, selected[:12]):
    ax.imshow(item["image"])
    ax.set_title(beans_label_names[item["labels"]])
    ax.axis("off")
plt.tight_layout()
plt.show()

# 4 imagens de exemplo para cada classe
n_examples = 4

fig, axes = plt.subplots(
    len(beans_label_names),
    n_examples,
    figsize=(12, 8)
)

for class_id, class_name in enumerate(beans_label_names):

    # Seleciona imagens desta classe
    class_items = [
        item for item in selected
        if item["labels"] == class_id
    ]

    # Mostra as primeiras n_examples
    for j in range(n_examples):

        item = class_items[j]

        axes[class_id, j].imshow(item["image"])
        axes[class_id, j].axis("off")

        # Coloca o nome da classe apenas no título
        axes[class_id, j].set_title(class_name)

plt.tight_layout()
plt.show()

"""### 3.3 Extraindo embeddings com DINOv2

Não faremos fine-tuning. O modelo será usado apenas como extrator de representação.
"""

import torch
from transformers import AutoImageProcessor, AutoModel

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

image_model_name = "facebook/dinov2-small"
image_processor = AutoImageProcessor.from_pretrained(image_model_name)
image_model = AutoModel.from_pretrained(image_model_name).to(device)
image_model.eval()

def extract_image_embeddings(items, batch_size=16):
    embeddings = []
    labels = []

    for start in range(0, len(items), batch_size):
        batch = items[start:start+batch_size]
        images = [item["image"].convert("RGB") for item in batch]
        y = [item["labels"] for item in batch]

        inputs = image_processor(images=images, return_tensors="pt").to(device)

        with torch.no_grad():
            outputs = image_model(**inputs)
            emb = outputs.pooler_output

        embeddings.append(emb.cpu().numpy())
        labels.extend(y)

    return np.vstack(embeddings), np.array(labels)

X_img, y_img = extract_image_embeddings(selected)
print("Formato dos embeddings:", X_img.shape)

"""### 3.4 Convertendo embeddings para DataFrame

Agora voltamos ao mundo tabular: **amostras × features**.
"""

img_feature_names = [f"f_{i:03d}" for i in range(X_img.shape[1])]

df_img = pd.DataFrame(X_img, columns=img_feature_names)
df_img["sample_id"] = df_img.index # Add a unique identifier
df_img["label"] = y_img
df_img["class_name"] = [beans_label_names[i] for i in y_img]

# Add original dataset split as metadata
# Assuming all 'selected' items are from the 'train' split after previous modification
df_img['original_split'] = 'train'

# Reorder columns to have id and metadata at the beginning
df_img = df_img[['sample_id', 'label', 'class_name', 'original_split'] + img_feature_names]

df_img.head()

"""# 4. EDA dos embeddings de imagem

Com centenas de features, visualizações diretas ficam difíceis.

Vamos usar PCA apenas como ferramenta de inspeção.
"""

from pandas.plotting import parallel_coordinates
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

# Padronizar as 384 features
X_img_scaled = StandardScaler().fit_transform(X_img)



# Criar DataFrame
feature_names = [f"f{i+1}" for i in range(X_img_scaled.shape[1])]

df_parallel_img = pd.DataFrame(
    X_img_scaled,
    columns=feature_names
)

# Converter IDs das classes para nomes
df_parallel_img["class_name"] = [
    beans_label_names[int(label)]
    for label in y_img
]

# --------------------------------------------------
# Selecionar poucas imagens por classe
# para o gráfico não ficar COMPLETAMENTE impossível
# --------------------------------------------------

n_samples_per_class = 5

parts = []

for class_name, group in df_parallel_img.groupby("class_name"):
    parts.append(
        group.sample(
            min(len(group), n_samples_per_class),
            random_state=RANDOM_STATE
        )
    )

sample_parallel_img = pd.concat(parts).reset_index(drop=True)

# --------------------------------------------------
# Parallel Coordinates com TODAS as 384 features
# --------------------------------------------------

plt.figure(figsize=(24, 8))

parallel_coordinates(
    sample_parallel_img,
    class_column="class_name",
    color=["red", "green", "blue"],
    alpha=0.55,
    linewidth=1.0
)

plt.title(
    "DINOv2 — Parallel Coordinates das 384 features",
    fontsize=16
)

plt.xlabel("Features do embedding DINOv2")
plt.ylabel("Z-score")

# Não mostrar os 384 nomes porque ficaria ilegível
plt.xticks([])

plt.grid(alpha=0.15)

plt.tight_layout()
plt.show()

"""> Complicado de enxergar essas 384 features de uma vez, certo? Talvez poderiamos olhar por janela de 20 em 20 features... mas nao teriamos uma noção global das features. Ou escolher 20 features aleatoriamente, como abaixo:"""

from pandas.plotting import parallel_coordinates
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# --------------------------------------------------
# 1. Escolher aleatoriamente 20 das 384 features
# --------------------------------------------------

rng = np.random.default_rng(42)

selected_feature_idx = rng.choice(
    X_img_scaled.shape[1],
    size=20,
    replace=False
)

# Ordenar apenas para facilitar a leitura
selected_feature_idx = np.sort(selected_feature_idx)

selected_feature_names = [
    f"f_{i:03d}" for i in selected_feature_idx
]

print("Features selecionadas:")
print(selected_feature_names)


# --------------------------------------------------
# 2. Criar DataFrame apenas com essas 20 features
# --------------------------------------------------

df_parallel_20 = pd.DataFrame(
    X_img_scaled[:, selected_feature_idx],
    columns=selected_feature_names
)

df_parallel_20["class_name"] = [
    beans_label_names[int(label)]
    for label in y_img
]


# --------------------------------------------------
# 3. Selecionar algumas imagens de cada classe
# --------------------------------------------------

n_samples_per_class = 10

parts = []

for class_name, group in df_parallel_20.groupby("class_name"):

    parts.append(
        group.sample(
            min(len(group), n_samples_per_class),
            random_state=RANDOM_STATE
        )
    )

sample_parallel_20 = pd.concat(parts).reset_index(drop=True)


# --------------------------------------------------
# 4. Parallel Coordinates
# --------------------------------------------------

plt.figure(figsize=(16, 7))

parallel_coordinates(
    sample_parallel_20,
    class_column="class_name",
    color=["red", "green", "blue"],
    alpha=0.55,
    linewidth=1.2
)

plt.title(
    "DINOv2 — 20 features aleatórias do embedding",
    fontsize=15
)

plt.xlabel("Features selecionadas")
plt.ylabel("Z-score")

plt.xticks(rotation=70)

plt.grid(alpha=0.2)

plt.tight_layout()
plt.show()

"""Agora vamos de PCA, um algoritmo de aprendizado de máquina para a redução de dimensionalidade."""

X_img_scaled = StandardScaler().fit_transform(X_img)

pca_img = PCA(n_components=8, random_state=RANDOM_STATE)
X_img_pca8 = pca_img.fit_transform(X_img_scaled)

print("Variância explicada acumulada (8 PCs):",
      pca_img.explained_variance_ratio_.sum())

var_acumulada = np.cumsum(
    pca_img.explained_variance_ratio_
)

plt.figure(figsize=(7,4))

plt.plot(
    range(1, 9),
    var_acumulada,
    marker="o"
)

plt.xlabel("Número de componentes")
plt.ylabel("Variância explicada acumulada")
plt.title("PCA — Variância explicada")
plt.grid(alpha=0.3)

plt.show()

df_img_pc = pd.DataFrame(
    X_img_pca8,
    columns=[f"PC{i+1}" for i in range(8)]
)

df_img_pc["class_name"] = df_img["class_name"].values


parts = []

for class_name, group in df_img_pc.groupby("class_name"):
    parts.append(
        group.sample(
            min(len(group), 15),
            random_state=RANDOM_STATE
        )
    )

sample_pc = pd.concat(parts).reset_index(drop=True)


plt.figure(figsize=(13, 5))

parallel_coordinates(
    sample_pc,
    class_column="class_name",
    color=["blue", "red", "green"],
    alpha=0.65,
    linewidth=1.4
)

plt.title("Beans + DINOv2 — Parallel Coordinates no espaço PCA")
plt.ylabel("Valor do componente principal")
plt.grid(alpha=0.2)

plt.tight_layout()
plt.show()

"""### 4.1 PCA em 3 dimensões

> **Pergunta:** as classes parecem separadas?
"""

import plotly.express as px
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import pandas as pd

# 1. Padronização das features do embedding
X_img_scaled = StandardScaler().fit_transform(X_img)

# 2. PCA: reduzir de 384 para 3 dimensões
pca_img_3d = PCA(n_components=3)

X_img_pca3 = pca_img_3d.fit_transform(X_img_scaled)

# Variância explicada por componente
print("Variância explicada:")
for i, var in enumerate(pca_img_3d.explained_variance_ratio_):
    print(f"PC{i+1}: {var*100:.2f}%")

print(
    f"\nVariância explicada acumulada: "
    f"{pca_img_3d.explained_variance_ratio_.sum()*100:.2f}%"
)

# 3. DataFrame para o Plotly
df_pca3 = pd.DataFrame(
    X_img_pca3,
    columns=["PC1", "PC2", "PC3"]
)

df_pca3["class_name"] = [
    beans_label_names[int(label)]
    for label in y_img
]

# 4. Scatter plot 3D
fig = px.scatter_3d(
    df_pca3,
    x="PC1",
    y="PC2",
    z="PC3",
    color="class_name",

    color_discrete_map={
        "angular_leaf_spot": "blue",
        "bean_rust": "red",
        "healthy": "green"
    },

    opacity=0.75,

    title="Beans + DINOv2 — PCA em 3 dimensões"
)

# Aumentar os pontos
fig.update_traces(
    marker=dict(size=6)
)

fig.update_layout(
    width=900,
    height=700
)

fig.show()

"""### 4.2 Procurando imagens atípicas no espaço de features"""

iso_img = IsolationForest(contamination=0.05, random_state=RANDOM_STATE)
img_outlier_pred = iso_img.fit_predict(X_img_scaled)

outlier_positions = np.where(img_outlier_pred == -1)[0]
print("Candidatos a outlier:", len(outlier_positions))

if len(outlier_positions) > 0:
    n_show = min(8, len(outlier_positions))
    fig, axes = plt.subplots(2, 4, figsize=(10,5))
    for ax in axes.flat:
        ax.axis("off")
    for ax, pos in zip(axes.flat, outlier_positions[:n_show]):
        ax.imshow(selected[pos]["image"])
        ax.set_title(beans_label_names[selected[pos]["labels"]])
        ax.axis("off")
    plt.tight_layout()
    plt.show()

"""### Discussão

- Esses outliers parecem realmente diferentes visualmente?
- São erros ou exemplos legítimos difíceis?
- Um ponto próximo de outra classe pode indicar ruído, erro de rótulo, ambiguidade real ou representação inadequada?

# 5. Texto: de sentenças para features com Sentence Transformers

## Dataset: AG News

Classes:

- World
- Sports
- Business
- Sci/Tech

## Pergunta

**Os embeddings semânticos organizam as notícias de acordo com seus temas?**

Fluxo:

**Texto → Sentence Transformer → embedding**
"""

from datasets import load_dataset

# Try updating the libraries first if this error persists
# !pip install -U datasets huggingface_hub

ag = load_dataset("ag_news")
ag

!pip install -U datasets huggingface_hub

"""### 5.1 Amostragem estratificada"""

N_TEXT_PER_CLASS = 120

text_items = []
for label_id in sorted(set(ag["train"]["label"])):
    subset = ag["train"].filter(lambda x: x["label"] == label_id)
    subset = subset.shuffle(seed=RANDOM_STATE).select(range(N_TEXT_PER_CLASS))
    text_items.extend([subset[i] for i in range(len(subset))])

ag_label_names = ["World", "Sports", "Business", "Sci/Tech"]

df_text_raw = pd.DataFrame({
    "text": [x["text"] for x in text_items],
    "label": [x["label"] for x in text_items],
})
df_text_raw["class_name"] = df_text_raw["label"].map(dict(enumerate(ag_label_names)))

df_text_raw.head()

"""### 5.2 EDA do texto bruto"""

df_text_raw["n_chars"] = df_text_raw["text"].str.len()
df_text_raw["n_words"] = df_text_raw["text"].str.split().str.len()

display(df_text_raw[["n_chars", "n_words"]].describe())

print("Duplicatas de texto:", df_text_raw["text"].duplicated().sum())
print("Textos vazios:", (df_text_raw["text"].str.strip() == "").sum())

display(df_text_raw["class_name"].value_counts())

"""### 5.3 Gerando embeddings textuais"""

from sentence_transformers import SentenceTransformer

text_model_name = "sentence-transformers/all-MiniLM-L6-v2"
text_model = SentenceTransformer(text_model_name, device=device)

X_text = text_model.encode(
    df_text_raw["text"].tolist(),
    batch_size=64,
    show_progress_bar=True,
    convert_to_numpy=True,
    normalize_embeddings=False
)

print("Formato dos embeddings:", X_text.shape)

text_feature_names = [f"f_{i:03d}" for i in range(X_text.shape[1])]

df_text = pd.DataFrame(X_text, columns=text_feature_names)
df_text["label"] = df_text_raw["label"].values
df_text["class_name"] = df_text_raw["class_name"].values

df_text.head()

"""# 6. EDA dos embeddings de texto"""

X_text_scaled = StandardScaler().fit_transform(X_text)

pca_text8 = PCA(n_components=8, random_state=RANDOM_STATE)
X_text_pca8 = pca_text8.fit_transform(X_text_scaled)

df_text_pc = pd.DataFrame(
    X_text_pca8,
    columns=[f"PC{i+1}" for i in range(8)]
)
df_text_pc["class_name"] = df_text["class_name"].values

parts = []
for class_name, group in df_text_pc.groupby("class_name"):
    parts.append(group.sample(min(len(group), 12), random_state=RANDOM_STATE))
sample_text_pc = pd.concat(parts).reset_index(drop=True)

plt.figure(figsize=(13,5))
parallel_coordinates(sample_text_pc, "class_name", alpha=0.3)
plt.title("AG News + MiniLM — Parallel Coordinates no espaço PCA")
plt.tight_layout()
plt.show()

pca_text2 = PCA(n_components=2, random_state=RANDOM_STATE)
X_text_2d = pca_text2.fit_transform(X_text_scaled)

plt.figure(figsize=(8,6))
for class_id, class_name in enumerate(ag_label_names):
    mask = df_text["label"].values == class_id
    plt.scatter(X_text_2d[mask,0], X_text_2d[mask,1], alpha=0.55, label=class_name)

plt.xlabel("PC1")
plt.ylabel("PC2")
plt.title("AG News + MiniLM — PCA 2D")
plt.legend()
plt.show()

"""### Discussão

- Quais classes parecem mais separadas?
- Quais se sobrepõem?
- PCA preserva toda a estrutura semântica?
- Um espaço pouco separável em 2D pode ainda ser classificável em alta dimensão?

# 7. Simulando problemas de qualidade em embeddings

Problemas também podem surgir depois do processamento:

- vetores ausentes;
- duplicatas;
- ruído;
- rótulos incorretos.
"""

df_text_dirty = df_text.copy()

# Missing
for col in text_feature_names[:3]:
    idx = np.random.choice(df_text_dirty.index, size=8, replace=False)
    df_text_dirty.loc[idx, col] = np.nan

# Duplicatas
df_text_dirty = pd.concat([df_text_dirty, df_text_dirty.iloc[:5]], ignore_index=True)

# Label noise
flip_idx = np.random.choice(df_text_dirty.index[:-5], size=12, replace=False)
df_text_dirty.loc[flip_idx, "label"] = np.random.randint(0, 4, size=len(flip_idx))
df_text_dirty["class_name"] = df_text_dirty["label"].map(dict(enumerate(ag_label_names)))

print("Missing nas primeiras features:")
display(df_text_dirty[text_feature_names[:6]].isna().sum())

print("Duplicatas completas:", df_text_dirty.duplicated().sum())

"""### Pergunta

Um embedding com `NaN` provavelmente foi causado pelo fenômeno real ou pelo pipeline?

**Problemas de qualidade podem surgir no dado bruto ou durante o processamento.**

# 8. Classificação simples como teste da representação

Hipótese:

> **Se as representações contêm informação discriminativa, um classificador simples deve alcançar desempenho razoável.**

Usaremos Regressão Logística para reduzir a interferência da complexidade do classificador.

## 8.1 Wine
"""

X_wine = StandardScaler().fit_transform(df_wine[feature_cols])
y_wine = df_wine["target"].values

X_train, X_test, y_train, y_test = train_test_split(
    X_wine, y_wine, test_size=0.25, stratify=y_wine, random_state=RANDOM_STATE
)

clf = LogisticRegression(max_iter=3000)
clf.fit(X_train, y_train)
pred = clf.predict(X_test)

print(classification_report(y_test, pred, target_names=list(wine.target_names)))
ConfusionMatrixDisplay.from_predictions(
    y_test, pred, display_labels=list(wine.target_names), xticks_rotation=45
)
plt.title("Wine — Logistic Regression")
plt.show()

"""## 8.2 Beans + DINOv2"""

X_train, X_test, y_train, y_test = train_test_split(
    X_img_scaled, y_img, test_size=0.25, stratify=y_img, random_state=RANDOM_STATE
)

clf = LogisticRegression(max_iter=3000)
clf.fit(X_train, y_train)
pred = clf.predict(X_test)

print(classification_report(y_test, pred, target_names=beans_label_names))
ConfusionMatrixDisplay.from_predictions(
    y_test, pred, display_labels=beans_label_names, xticks_rotation=45
)
plt.title("Beans + DINOv2 — Logistic Regression")
plt.show()

"""## 8.3 AG News + MiniLM"""

y_text = df_text["label"].values

X_train, X_test, y_train, y_test = train_test_split(
    X_text_scaled, y_text, test_size=0.25, stratify=y_text, random_state=RANDOM_STATE
)

clf = LogisticRegression(max_iter=3000)
clf.fit(X_train, y_train)
pred = clf.predict(X_test)

print(classification_report(y_test, pred, target_names=ag_label_names))
ConfusionMatrixDisplay.from_predictions(
    y_test, pred, display_labels=ag_label_names, xticks_rotation=45
)
plt.title("AG News + MiniLM — Logistic Regression")
plt.show()

"""# 9. Síntese

| Modalidade | Dado bruto | Representação usada na EDA | Problema |
|---|---|---|---|
| Tabular | atributos químicos | features originais | classificação de vinho |
| Imagem | pixels | DINOv2 embeddings | doença da folha |
| Texto | notícia | MiniLM embeddings | tema da notícia |

## Mensagem central

**Pergunta → representação → qualidade → exploração → hipótese → classificação**

### Perguntas finais

1. O que significa uma “boa feature”?
2. Um embedding excelente dispensa EDA?
3. Outliers em embeddings são mais difíceis de interpretar que outliers em atributos físicos?
4. Como detectar um label errado em imagem ou texto?
5. Em que momento uma visualização 2D pode induzir conclusões erradas?

# 10. Atividade para os alunos

Escolha **uma** modalidade e produza um pequeno relatório com:

1. Pergunta de investigação.
2. Unidade de análise.
3. Features utilizadas.
4. Uma análise de qualidade.
5. Uma visualização univariada ou multivariada.
6. Uma projeção PCA 2D.
7. Uma hipótese sobre separabilidade das classes.
8. Um teste com Regressão Logística.
9. Uma limitação da análise.

## Extensões opcionais

- inserir label noise e medir impacto;
- usar UMAP apenas como extensão;
- comparar Isolation Forest com distância ao centroide;
- identificar possíveis duplicatas semânticas em texto;
- procurar imagens suspeitas de erro de rótulo.

# Referências e recursos

- Oquab et al. — **DINOv2: Learning Robust Visual Features without Supervision**.
- Hugging Face Transformers — documentação do DINOv2.
- Makerere AI Lab — **Beans**.
- **AG News** — benchmark de classificação de tópicos.
- Sentence Transformers — `all-MiniLM-L6-v2`.

> Para fins didáticos, trabalhamos com subconjuntos pequenos para que o notebook execute rapidamente no Google Colab.
"""