# -*- coding: utf-8 -*-
"""Pratica_Embeddings_Texto_Portugues_PCA_KMeans.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W6fkY3WiwwpzfwLWJ2BoQAjOY5zJLocK

# Prática de Ciência de Dados
## Embeddings de textos em português, PCA e K-Means

Nesta prática vamos trabalhar com **150 textos em português**, distribuídos em diferentes contextos temáticos.

O objetivo é transformar textos em vetores numéricos (**embeddings**) e verificar se um algoritmo de aprendizado não supervisionado consegue identificar estruturas semelhantes às categorias originais.

As categorias reais serão mantidas no dataset, mas **não serão utilizadas pelo K-Means**.

## 1. Instalação e importação das bibliotecas

Vamos utilizar um modelo multilíngue da biblioteca `sentence-transformers`.
"""

!pip -q install sentence-transformers

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sentence_transformers import SentenceTransformer
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.preprocessing import normalize

"""## Exemplos para extrair vetores de características de imagens"""

import torch
from transformers import AutoImageProcessor, AutoModel

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

image_model_name = "facebook/dinov2-large"
image_processor = AutoImageProcessor.from_pretrained(image_model_name)
image_model = AutoModel.from_pretrained(image_model_name).to(device)
image_model.eval()

from PIL import Image

imageC = Image.open("/content/cachorro.jpeg").convert("RGB")
imageG = Image.open("/content/gato.jpeg").convert("RGB")
imageCV = Image.open("/content/cavalo.jpeg").convert("RGB")
imageP = Image.open("/content/passaro.jpeg").convert("RGB")
print(type(imageC))

from PIL import Image

def extract_image_embedding(image):

    inputs = image_processor(
        images=image,
        return_tensors="pt"
    ).to(device)

    with torch.no_grad():
        outputs = image_model(**inputs)
        embedding = outputs.pooler_output

    return embedding.squeeze(0).cpu().numpy()

emb1 = extract_image_embedding(imageC)
emb2 = extract_image_embedding(imageG)
emb3 = extract_image_embedding(imageCV)
emb4 = extract_image_embedding(imageP)

print(emb1.shape)
print(emb2.shape)
print(emb3.shape)
print(emb3)
print(emb1)
print(emb2)

"""Para visualizar os 1024 atributos, vamos criar um novo DataFrame onde cada linha é um dos seus vetores `emb` e cada coluna corresponde a uma das 1024 dimensões do embedding."""

df_attributes = pd.DataFrame([emb1, emb2, emb3, emb4])

print("Formato do novo DataFrame (número de embeddings, número de atributos):", df_attributes.shape)

# Agora, apply describe() para ver as estatísticas para cada um dos 1024 atributos
display(df_attributes.describe())

import matplotlib.pyplot as plt
import pandas.plotting as pp

# Criar uma cópia do DataFrame para adicionar a coluna de classe sem modificar o original
df_attributes_plot = df_attributes.copy()

# Adicionar uma coluna de 'embedding_id' para ser usada como a coluna de classe
df_attributes_plot['embedding_id'] = ['emb1', 'emb2', 'emb3', 'emb4']

# Selecionar apenas os 10 primeiros atributos (colunas) e a coluna 'embedding_id'
num_attributes_to_plot = 10
df_attributes_plot_subset = df_attributes_plot.iloc[:, :num_attributes_to_plot].copy()
df_attributes_plot_subset['embedding_id'] = df_attributes_plot['embedding_id']

print(f"Plotando os {num_attributes_to_plot} primeiros atributos.")

# Plotar o gráfico de coordenadas paralelas
plt.figure(figsize=(15, 7)) # Ajustar o tamanho da figura para 10 atributos
pp.parallel_coordinates(
    df_attributes_plot_subset,
    'embedding_id', # Coluna usada para colorir as linhas
    colormap='viridis' # Escolher um mapa de cores
)

plt.title(f'Gráfico de Coordenadas Paralelas dos {num_attributes_to_plot} Primeiros Atributos dos Embeddings de Imagem')
plt.xlabel('Índice do Atributo')
plt.ylabel('Valor do Atributo')
plt.xticks(rotation=45, ha='right') # Reabilitar e rotacionar os rótulos do eixo X para 10 atributos
plt.legend(title='Embedding', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

"""## 2. Carregamento dos textos

Faça upload do arquivo `dataset_150_textos_portugues.csv` no Colab ou monte seu Google Drive.
"""

df = pd.read_csv("dataset_150_textos_portugues.csv")

df.head(50)

print("Quantidade de textos:", len(df))
print("Categorias disponíveis:")
print(df["categoria"].value_counts())

"""## 3. Observando alguns textos"""

for i in range(50):
    print(f'{i+1}. [{df.loc[i, "categoria"]}] {df.loc[i, "texto"]}')

"""## 4. Geração dos embeddings

Um **embedding** é uma representação vetorial de um texto.

Textos semanticamente parecidos tendem a produzir vetores próximos no espaço de embeddings.

Vamos utilizar o modelo:

[`paraphrase-multilingual-MiniLM-L12-v2`](https://huggingface.co/sentence-transformers/models)

Esse modelo gera embeddings para vários idiomas, incluindo português.
"""

modelo = SentenceTransformer(
    "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
)

textos = df["texto"].tolist()

embeddings = modelo.encode(
    textos,
    convert_to_numpy=True,
    show_progress_bar=True
)

print("Formato dos embeddings:", embeddings.shape)

print(embeddings[0,:10])
print(textos[0])

print(embeddings[7,:10])
print(textos[7])

print(embeddings[50,:10])
print(textos[50])

from sklearn.metrics.pairwise import cosine_similarity

# Calculando a similaridade do cosseno entre embeddings[0] e embeddings[1]
similarity_0_1 = cosine_similarity(embeddings[0].reshape(1, -1), embeddings[7].reshape(1, -1))[0][0]

# Calculando a similaridade do cosseno entre embeddings[0] e embeddings[50]
similarity_0_50 = cosine_similarity(embeddings[0].reshape(1, -1), embeddings[50].reshape(1, -1))[0][0]

print(f"Similaridade do cosseno entre embeddings[0] e embeddings[1]: {similarity_0_1:.4f}")
print(f"Similaridade do cosseno entre embeddings[0] e embeddings[50]: {similarity_0_50:.4f}")

"""Cada linha da matriz corresponde a um texto.

Cada coluna corresponde a uma dimensão do espaço vetorial produzido pelo modelo.
"""

embeddings[0]

"""## 5. Normalização dos embeddings

Para representações semânticas, é comum normalizar os vetores para comprimento 1.

Isso torna a geometria baseada em direção mais próxima da similaridade cosseno.
"""

X = normalize(embeddings, norm="l2")

print("Formato:", X.shape)
print("Norma do primeiro vetor:", np.linalg.norm(X[0]))

"""## 6. PCA para visualização

Os embeddings possuem muitas dimensões e não podem ser visualizados diretamente.

Vamos utilizar PCA para projetar os vetores em duas dimensões.
"""

pca = PCA(n_components=3)

X_pca = pca.fit_transform(X)

print("Formato original:", X.shape)
print("Formato após PCA:", X_pca.shape)

for i, valor in enumerate(pca.explained_variance_ratio_):
    print(f"PC{i+1}: {valor * 100:.2f}%")

print(
    "Variância explicada total:",
    f"{pca.explained_variance_ratio_.sum() * 100:.2f}%"
)

"""Uma porcentagem baixa de variância explicada em duas componentes não significa que os embeddings sejam ruins.

Significa apenas que **duas dimensões não conseguem representar toda a estrutura existente no espaço original**.
"""

plt.figure(figsize=(9, 7))

plt.scatter(
    X_pca[:, 0],
    X_pca[:, 1]
)

plt.xlabel("PC1")
plt.ylabel("PC2")
plt.title("Embeddings de textos projetados com PCA")

plt.show()

"""### Observe antes de utilizar as categorias reais

- Existem regiões de maior concentração?
- Alguns pontos parecem formar grupos?
- Quantos grupos parecem existir?
- Há sobreposição entre regiões?

# 7. Agrupamento com K-Means

Vamos aplicar K-Means diretamente sobre os embeddings normalizados.

As categorias reais dos textos **não serão utilizadas** no treinamento.
"""

kmeans = KMeans(
    n_clusters=6,
    random_state=42,
    n_init="auto"
)

clusters = kmeans.fit_predict(X)

df["cluster"] = clusters

df[["texto", "cluster"]].head(50)

df["cluster"].value_counts().sort_index()

"""## 8. Visualização dos clusters no PCA"""

plt.figure(figsize=(9, 7))

plt.scatter(
    X_pca[:, 0],
    X_pca[:, 1],
    c=clusters
)

plt.xlabel("PC1")
plt.ylabel("PC2")
plt.title("Clusters encontrados pelo K-Means")

plt.show()

import plotly.express as px

# Criar um DataFrame temporário para o Plotly
df_pca_3d = pd.DataFrame(X_pca, columns=['PC1', 'PC2', 'PC3'])
df_pca_3d['categoria'] = clusters

fig = px.scatter_3d(
    df_pca_3d,
    x='PC1',
    y='PC2',
    z='PC3',
    color='categoria',
    title='Embeddings de Textos Projetados com PCA (3D)',
    hover_name='categoria',
    height=600
)
fig.update_traces(marker=dict(size=5, opacity=0.8))
fig.show()

"""O K-Means foi executado no espaço completo dos embeddings.

O PCA foi utilizado apenas para criar uma representação bidimensional dos resultados.

# 9. Método do cotovelo
"""

inertias = []

valores_k = range(2, 11)

for k in valores_k:
    modelo_k = KMeans(
        n_clusters=k,
        random_state=42,
        n_init="auto"
    )

    modelo_k.fit(X)
    inertias.append(modelo_k.inertia_)

plt.figure(figsize=(8, 5))
plt.plot(valores_k, inertias, marker="o")

plt.xlabel("Número de clusters (K)")
plt.ylabel("Inércia")
plt.title("Método do cotovelo")

plt.show()

"""# 10. Silhouette Score"""

scores = []

for k in range(2, 11):

    modelo_k = KMeans(
        n_clusters=k,
        random_state=42,
        n_init="auto"
    )

    labels = modelo_k.fit_predict(X)

    score = silhouette_score(
        X,
        labels,
        metric="euclidean"
    )

    scores.append(score)
    print(f"K = {k}: {score:.4f}")

plt.figure(figsize=(8, 5))

plt.plot(
    range(2, 11),
    scores,
    marker="o"
)

plt.xlabel("Número de clusters (K)")
plt.ylabel("Silhouette Score")
plt.title("Silhouette Score")

plt.show()

"""# 11. Comparação com as categorias reais

Somente agora vamos utilizar as categorias do dataset.

Essa comparação ajuda a verificar se os grupos encontrados pelo K-Means possuem alguma relação com os contextos semânticos utilizados na criação dos textos.
"""

pd.crosstab(
    df["categoria"],
    df["cluster"]
)

"""## Visualização das categorias verdadeiras"""

categorias = df["categoria"].astype("category")
codigos = categorias.cat.codes

plt.figure(figsize=(9, 7))

scatter = plt.scatter(
    X_pca[:, 0],
    X_pca[:, 1],
    c=codigos
)

plt.xlabel("PC1")
plt.ylabel("PC2")
plt.title("Categorias reais projetadas no PCA")

plt.show()

"""# 12. Inspecionando os textos de cada cluster

Uma etapa importante em clustering é interpretar semanticamente os grupos encontrados.
"""

for cluster_id in sorted(df["cluster"].unique()):

    print("\n" + "=" * 70)
    print("CLUSTER", cluster_id)
    print("=" * 70)

    exemplos = df[df["cluster"] == cluster_id].head(10)

    for texto in exemplos["texto"]:
        print("-", texto)

"""# 13. Questões

1. O PCA mostrou separação clara entre os textos?
2. Qual porcentagem da variância foi explicada pelas duas primeiras componentes?
3. Qual valor de K parece mais adequado pelo método do cotovelo?
4. Qual K apresentou o maior Silhouette Score?
5. Os clusters encontrados coincidem com as categorias utilizadas para gerar os textos?
6. Quais categorias ficaram mais bem separadas?
7. Quais categorias apresentaram maior sobreposição?
8. Analise alguns textos que foram agrupados de forma inesperada. Existe alguma semelhança semântica que explique o resultado?
9. Por que os rótulos não foram utilizados durante o K-Means?
10. Por que cluster e classe não são necessariamente a mesma coisa?
"""